# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Edward Im Blog
tagline:             'Researcher'
description:         ''
url:                 https://tigerk0430.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Edward Im
  url:               https://tigerk0430.github.io
  email:             gyurse@gmail.com

# Custom vars
version:             1.0.0

plugins: [jekyll-paginate]

# Tag setting
#collections:
#  tags:
#    output: true
#    permalink: /tags/:path/

#defaults:
#  - scope:
#      path: ''
#      type: tags
#    values:
#      layout: tag

google_analytics:
  ua: 'UA-109898110-1'

github:
  repo: 'https://github.com/tigerk0430/tigerk0430.github.io'

category_dir: category/
tag_dir: tag/

excerpt_separator: ""
