# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               lockdpwn's blog
tagline:             "Researcher & Engineer & Tech Evangelist"
description:         ''
url:                 https://tigerk0430.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Edward Im
  url:               https://tigerk0430.github.io
  email:             gyurse@gmail.com

# Disqus
discus-identifier: tigerk0430-github-io # add your discus identifier
  
# Custom vars
version:             1.0.0

plugins: [jekyll-paginate]

# Tag setting
#collections:
#  tags:
#    output: true
#    permalink: /tags/:path/

#defaults:
#  - scope:
#      path: ''
#      type: tags
#    values:
#      layout: tag

google_analytics:
  ua: 'UA-109898110-1'

github:
  repo: 'https://github.com/tigerk0430/tigerk0430.github.io'

category_dir: category/
tag_dir: tag/

excerpt_separator: ""

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
    - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
